# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-07 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_country_countrycount'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='alpha_two',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
