# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-07 09:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_country_alpha_two'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='location',
        ),
        migrations.RemoveField(
            model_name='country',
            name='picture',
        ),
    ]
