# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-07 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_memory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrycount',
            name='count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
