# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-07 11:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20160807_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 8, 7, 11, 57, 47, 213985, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
