# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-07 17:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_memory_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='countryname',
        ),
    ]
