# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-08 20:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_remove_country_countryname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('description', models.CharField(blank=True, max_length=10000, null=True)),
                ('country_combo', models.ManyToManyField(to='profiles.Country')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='award',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.Award'),
        ),
    ]
